trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'install node.js'
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: 'install'
  - task: Npm@1
    displayName: 'npm run-script build'
    inputs:
      command: 'custom'
      customCommand: 'run-script build'
