# ===================================================================
# Standard Spring Boot properties...  Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:

  # ContextIdApplicationContextInitializer
  application.name: scv-prototype-api

  # NOTE: the order is important; if you add any, keep 'overrides' at the end
  profiles.include: overrides

# ===================================================================
# Management interface properties...
# ===================================================================

management:
  endpoint:
    # TODO :: GjB :: remove this (eventually)
    health.show-details: always
  endpoints:
    web.exposure.include: '*'

# ===================================================================
# Application specific properties...
# ===================================================================

application:
  config:
    service:
      interop:
        base-uri: # must be set externally
        proxy-host: # (optional) must be set externally
        proxy-port: # (optional) must be set externally
    webmvc:
      cors-allowed-origins: # must be set externally
  jwt-resolver:
    expiration-time: 20m
    issuer: # must be set externally
    secret: # must be set externally

  # see ca.gov.portal.scv.api.security.InMemoryUserDetailsService
  # TODO :: GjB :: remove this (eventually)
  in-memory-user-details-service.enabled: true
