# ===================================================================
# Standard Spring Boot properties...  Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# Spring Boot Auto Configuration debug flag
# debug: true

spring:
  # allow a 'local' profile for further customization
  # (note application-local.yml will be ignored by git)
  profiles.include: local

# ===================================================================
# Logging properties...
# ===================================================================

logging.level:
  ca.gov.portal.scv.api: trace
  org.springframework: debug

# ===================================================================
# Application specific properties...
# ===================================================================

application:
  config:
    security:
      ignored-paths:
        - /actuator/**
    service:
      interop:
        location:
          base-uri: https://location.okd.azure.sc-interop.ca/
          proxy-host: proxy.prv
          proxy-port: 80
        person:
          base-uri: https://person.okd.azure.sc-interop.ca/
          proxy-host: proxy.prv
          proxy-port: 80
    webmvc:
      cors-allowed-origins:
          - http://localhost:3000
  jwt-resolver:
    issuer: http://localhost:8080/
    secret: > # random 128 byte string
      z2U^0K5dvxYE9u#2IpKk*ui6T6lYv1j&wMnM!Flkt&oo7F&er!bQQ#6KXHz1qQlP
      hNTE$kzz65WY4whD5sQW5WpRA89Lq2^8Ysyh7mc&h&6$jIUqeu0Dn3nMYJNSVGaQ
